Feature deployment configuration
BrightCoders-Institute/BCDIC22-RoR-reloj-checador-team1 pull request #21
Opened 2023-01-26 21:26 UTC by AangelF

# Description

Add necessary files to deploy the website on Render.com and edit the configuration on other files.
The files edited were:
- puma.rb
- production.rb

The files added were:
- render-build.sh
- **database.yml** (this file is necessary for production).

2023-01-26 21:33 UTC, juperameza requested changes

2023-01-26 21:33 UTC, juperameza commented on app/views/admins/index.html.erb
> +</main>
Add a new line at the end of this file

2023-01-26 21:33 UTC, juperameza commented on bin/render-build.sh
> +bundle exec rake db:migrate
New line at the end of this file

2023-01-26 21:33 UTC, juperameza commented on db/seeds.rb
> +admin = Admin.create(admin: 1, privateNumber: 123456)
New line at the end of this file

2023-01-26 21:33 UTC, juperameza commented on app/controllers/admins_controller.rb
> +    params.require(:admin).permit(:admin, :privateNumber)
I recommend you use devise gem but this is ok

2023-01-26 21:53 UTC, oscaregr requested changes

2023-01-26 21:53 UTC, oscaregr commented on app/helpers/logins_admins_helper.rb
> +module LoginsAdminsHelper
if you no use this remove

2023-01-26 21:53 UTC, oscaregr commented on app/helpers/admins_helper.rb
> +end
same here, if you no use this remove

2023-01-26 21:53 UTC, oscaregr commented on app/controllers/admins_controller.rb
> +end
add one line blanck, here

2023-01-26 21:53 UTC, oscaregr commented on app/views/admins/index.html.erb
> +</main>
add one line blanck

2023-01-26 22:01 UTC, xManuel007 approved these changes

2023-01-26 22:18 UTC, oscaregr requested changes
do this, and i made the approve

2023-01-26 22:18 UTC, oscaregr commented on app/views/admins/index.html.erb
> +</main>
add line blanck , and be sure, open the file in github and check blanck is add

2023-01-26 22:18 UTC, oscaregr commented on app/controllers/admins_controller.rb
> +end
add line blanck under the last end

2023-01-27 03:46 UTC, dagp-ucol approved these changes
I see that you resolved some other issues.
Be careful with good practices.

I know this comments may be frustrating, but the objective of the bootcamp is to ensure that you are learning but also with good practices.

PR looks good to me, just be careful.

2023-01-27 03:46 UTC, dagp-ucol commented on test/models/administrator_test.rb
> +  # end
Hey, remember to delete unused code when generating files, controllers, models, etc.

2023-01-27 03:46 UTC, dagp-ucol commented on test/models/admin_test.rb
> +  # end
Hey, remember to delete unused code when generating files, controllers, models, etc.

2023-01-27 21:17 UTC, oscaregr approved these changes
LGTM

2023-01-27 21:18 UTC, juperameza approved these changes
Lgtm

2023-01-27 21:19 UTC, merged