Attendances reports
BrightCoders-Institute/BCDIC22-RoR-reloj-checador-team1 pull request #31
Opened 2023-02-07 23:01 UTC by AlanGonzalezM

# Description

What did you implemented/Why did you implemented this:

- This feature allows to inform the admin about the attendance information.
- At first, it shows a table specifying the time and date of the check-in and check-out by the employee.
- Then, shows the average per hour when employees register their check-in /check-out. 
- At last, the admin can see a table that contains all the absences by employees.

## Testing

Run the commands:
`rails db:create`
`rails db:migrate`
`rails db:seed`

Run the server:
`rails serve`

## Screenshots

![image](https://user-images.githubusercontent.com/55168400/217386232-70cef773-da95-46f0-8532-eff29010fb2b.png)
![image](https://user-images.githubusercontent.com/55168400/217386280-6fe0f2ee-7e7f-41f5-bf6e-a39e648c4215.png)

2023-02-07 23:28 UTC, xManuel007 approved these changes

2023-02-07 23:31 UTC, oscaregr requested changes

2023-02-07 23:31 UTC, oscaregr commented on app/views/attendances/index.html.erb
> +</div>
add one line balnck here

2023-02-07 23:35 UTC, oscaregr approved these changes
LGTM

2023-02-08 17:47 UTC, juperameza approved these changes
Lg

2023-02-08 21:29 UTC, merged